<?php

return [

    /* All authenctication related messages are mentioned below */

    'AuthMessages' => [
        'NotVerified' => 'Your email is not verified yet! Please verify it first for accessing account.',
        'NotActive' => 'Your account is not activated yet. Please contact to admin!',
        'AccountDelete' => 'This account is permanently deleted from the system. Please contact to administration.',
        'InvalidCredentials' => 'Email & Password are incorrect.',
        'RoleNotFound' => 'These credentials do not match our records. Please contact to admin!',
        'CustomerEmailAlreadyExists' => 'Email is already exists. Kindly use another email.',
        'EmailNotFound' => 'Sorry the email you entered is not available in our record!',
        'EmailSentSuccess' => 'Reset password mail has been successfully sent to your email please check and verify.',
        'EmailExists' => 'Email is already exists',
        'PhoneExists' => 'Phone is already exists',
        'AccountNotFound' => "account does not exist!",
        'InvalidEmail' => "Invalid email address. Try again.",
        'InvalidPassword' => "Invalid password. Try again.",
        'InvalidPhone' => "Invalid mobile number. Try again.",
        'InvalidPhoneForgot' => "We're sorry. We weren't able to identify you given the information provided. Please enter email address.",
        'InvalidEmailForgot' => "We're sorry. We weren't able to identify you given the information provided.",
        'notVerified' => "Your Email is not verified please verify it from link in your registered email.",
        'notVerifiedByAdmin' => "Your Email is not verified by admin it will be verified soon.",
        'notApproved' => "Your Email is blocked by admin please contact administrator.",
        'subscriptionExpired' => "Your subscription expired.",
    ],

    'Users' => [
        'AddUserSuccess' => 'User added successfully!',
        'UpdateUserSuccess' => 'User updated successfully!',
        'FanUpdate' => 'Fan Updated Successfully'
    ],

    'Role' => [
        'RoleAddSuccess' => 'Role added successfully!',
        'RoleUpdateSuccess' => 'Role updated successfully!'
    ],

    'Customer' => [
        'RegisterMailSent' => 'Registration mail sent successfully. Please check your mail for verify account.',
    ],
    'LocationGroup' => [
        'AreaExists' => 'Area already exists in another location.',
        'GroupExists' => 'Group name already exists in another location.',
    ],
    'SlotAllocation' => [
        'Add' => 'Slot added successfully.',
        'Update' => 'Slot updated successfully.',
    ],
    "frontendMessages" =>[
        'LikedSong'=>'{PARAM} added to favourites',
        'UnlikedSong'=>'{PARAM} removed from favourites',
        'LikedArtist'=>'{PARAM} added to favourites',
        'UnlikedArtist'=>'{PARAM} removed from favourites',
        'LikedDynamicGroups'=>'{PARAM} added to favourites',
        'UnkikedDynamicGroups'=>'{PARAM} removed from your favourites',
        'ContactUs'=>'Your message submitted to fanclub Ltd.',
        'OtpSend'=>'We have sent a OTP on your email address',
        'ResendOtp'=>'We have sent a OTP on your email address',
        'DownloadSong'=>'{PARAM} downloaded successfully',
        'LoginFailed'=>'Invalid Login Details. Try again.',
        'ForgotPassword'=>'Reset password link has been sent on your email address',
        'ResetPassword'=>'Password has been reset successfully',
        'SongAddedIntoCustomPlaylist'=>'Successfully added to your playlist',
        'RemoveSongFromCustomPlaylist'=>'{PARAM} removed from your playlist',
        'PlaylistCreatedAndAddedSong'=>'Playlist {PARAM} has been created and added song into playlist',
        'UpdateCustomPlaylistName'=>'Your playlist updated successfully',
        'DeleteCustomPlaylist'=>'Your playlist deleted successfully',
        'EventAdded'=>'Event added in your profile',
        'EventUpdated'=>'Event updated in your profile',
        'EventRemoved'=>'Event removed from your profile',
        'NewsAdded'=>'News added in your profile',
        'NewsUpdated'=>'News updated in your profile',
        'NewsRemoved'=>'News removed from your profile',
        'BannerAdded'=>'Banner added in your profile',
        'BannerRemoved'=>'Banner removed from your profile',
        'SubscriptionSuccess'=>'You are subscribed successfully',
        'SubscriptionCancelled'=>'Your subscription has been cancelled successfully. You can still use enjoy music till {PARAM}',
        'SubscriptionUpgraded'=>'Your monthly subscription has been upgraded to Yearly plan',
        'SubscriptionUpgradFailed'=>'Failed',
        'SubscriptionCancelFailed'=>'Failed',
        'AddReview'=>'Review on {PARAM} added successfully',
        'RemoveReview'=>'Review on {PARAM} removed successfully',
        'UpdateReview'=>'Review on {PARAM} updated successfully',
        'ReviewUnapprovedByArtist'=>'Review on {PARAM} unapproved successfully',
        'ForumTopicLiked'=>'Thank you for liking this topic',
        // 'ForumTopicUnliked'=>'No message required for this',
        'ForumTopicUnliked'=>'You have unlike this topic',
        'ForumCommentAdded'=>'Your comment added on {PARAM} successfully',
        'ForumCommentRemovedByUser'=>'Your comment removed from {PARAM} successfully',
        'ForumCommentLiked'=>'Thank you for liking this comment',
        // 'ForumCommentUnliked'=>'No message required for this',
        'ForumCommentUnliked'=>'You have unlike this comment',
        'UplaodSongByArtist'=> 'We are making your video great. You will be notified once your video is published.',
        'UpdateSongDetail'=> 'Song Details are updated successfully',
        'UpdateSongDetailFail'=> 'You don`t have rights to update details of this song.',
        // 'UplaodSongByArtist'=>'{PARAM} added to fanclub library',
        'ProfileUpdate'=>'Your profile details updated successfully',
        'SecurityQuestionUpdates'=>'Your security question\'s details updated successfully',
        'SecurityQuestionAdded'=>'Your security question\'s added successfully',
        'SecurityQuestionDelete'=>'Your security question\'s deleted successfully',
        'RecoverAccountSuccessfullyFromSecurityQuestions'=>'Great! Your account information has been recovered.',
        'RecoverAccountFailedFromSecurityQuestions'=>'Sorry, your answers are not matching with our system. Please give correct answers to recover your account information.',
        'ArtistSignup'=>'Thank you for your registration with fanclub Ltd. We will review your profile and get back to you.',
        'ChatMessageNew'=>'Your Message to {PARAM} sent successfully.',
        'ChatListPersons'=>'Your Message List Retrived',
        'clearChat'=>'Your conversation has been deleted.',
        'readChat'=>'Your Message marked as read',
        'SearchNoResults'=>'No results found for your search criteria.',
        "artistNewsNotFound" => "No news articles posted by this artist yet.",
        // "artistNewsNotFound" => "There are no news from this Artist at this moment.",
        "artistEventNotFound" => "There are no upcoming events from this Artist at this moment.",
        "searchTagRemoved" => "Search tag removed successfully.",
        "allowMessage" => "Setting has been changed successfully.",
        "messageToArtistNotAllowed" => "{PARAM} is not available for message at this moment. ",
    ],
    'paymentStatus' => [
        'success' => 'Transaction was successful',
        'badcard' => 'Transaction failed due to decline from processor',
        'problem' => 'Transaction failed due to problem unrelated to credit card',
        'fraud' => 'Transaction failed due to failure of FraudTrack2 filter settings',
    ],
];
